apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-framework-client-3
  namespace: fschwanck
  labels:
    app.kubernetes.io/component: fl-framework
    app.kubernetes.io/name: fl-framework-client-3
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: fl-framework
      app.kubernetes.io/name: fl-framework-client-3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fl-framework
        app.kubernetes.io/name: fl-framework-client-3
    spec:
      volumes:
        - name: fl-dataset
          persistentVolumeClaim:
            claimName: fl-framework-storageclaim
      containers:
        - name: fl-framework-client-3
          imagePullPolicy: Always
          image: 'fschwanck/fl-framework-client:latest'
          env:
            - name: FL_CLIENT_DEVICE
              value: cpu
            - name: CERTIFICATES_PATH
              value: ./.cache/certificates
            - name: SERVER_ADDRESS
              value: fl-framework-server:8080
            - name: DATA_PATH
              value: ./data/cifar-10
            - name: DATA_BATCH_NUMBER
              value: '1'
          volumeMounts:
            - name: fl-dataset
              mountPath: /data
      nodeSelector:
        kubernetes.io/hostname: mac-porvir-03
