apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-framework-server
  namespace: fschwanck
  labels:
    app.kubernetes.io/component: fl-framework
    app.kubernetes.io/name: fl-framework-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: fl-framework
      app.kubernetes.io/name: fl-framework-server
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fl-framework
        app.kubernetes.io/name: fl-framework-server
    spec:
      containers:
        - name: flserver
          image: 'fschwanck/fl-framework-server:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - name: flserver
              containerPort: 8080
          env:
            - name: SERVER_NUM_ROUNDS
              value: '10'
            - name: CERTIFICATES_PATH
              value: ./.cache/certificates
            - name: SERVER_ADDRESS
              value: 0.0.0.0:8080
            - name: FRACTION_FIT
              value: '1'
            - name: MIN_FIT_CLIENTS
              value: '3'
            - name: MIN_AVAILABLE_CLIENTS
              value: '5'
            - name: CLIENT_LOCAL_EPOCHS
              value: '3'
            - name: FLWR_TELEMETRY_ENABLED
              value: '0'
            - name: SERVER_NAME
              value: fl-framework-server
          volumeMounts:
            - name: fl-dataset
              mountPath: /data
      volumes:
        - name: fl-dataset
          persistentVolumeClaim:
            claimName: fl-framework-storageclaim
      nodeSelector:
        kubernetes.io/hostname: brix-porvir-01
